### ISSUE TITLE
Question: how were stubs in this repo generated?

### ISSUE THREAD

**Issue by FrancescElies** [blakeNaccarato/pylance-stubs-unofficial#3]
Hi,

I am just curios what was the process of generating these stubs? Did you use pyright for that? Are there any parts that were manually crafted?

Thanks in advance

**Comment by blakeNaccarato** [comment]
On all of my local machines (work, home, etc...) I have VSCode installed as well as the Pylance extension. The stubs are at `~/.vscode/extensions/ms-python.vscode-pylance<VERSION>/dist/bundled/stubs`, where `<VERSION>` corresponds to the Pylance extension version you have installed. I scrape those stubs with a [script](https://github.com/blakeNaccarato/pylance-stubs-unofficial/blob/main/update.ps1) that I use to update this repo. The script grabs these stubs and pushes them to this repo under a tag matching the `<VERSION>`, then I manually publish a release in the GitHub UI.

#### More details...

It works well enough for now, but if I lag the Pylance release cycle somewhat, it's because I'm doing this manually when I notice that Pylance has updated. It is conceivable that a GitHub Actions runner could be configured with VSCode and Pylance installed, and then grab those stubs and push automatically.

Alternatively, it could be automated by going directly to the source, and grabbing stubs from the source where the Pylance team gets them from. They bundle a curated set of stubs from https://github.com/microsoft/python-type-stubs in each release. But there is no telling which commit over at https://github.com/microsoft/python-type-stubs corresponds to what is bundled in a given Pylance version, and they curate it in a certain way, so I just scrape Pylance's stubs from my local machine whenever it updates.

This way I can pull these stubs as a submodule to my project runners in CI, and they get (mostly) the same stubs as I have locally, and it quiets down the CI complaints when running `pyright`. It's not perfect, since there are more stubs in `~/.vscode/extensions/ms-python.vscode-pylance<VERSION>/dist` that I'm not scraping. But I don't know how Pylance composes those additional stubs and uses them, so I just grab the main one and it fixes the lion's share of the discrepancies.

**Comment by blakeNaccarato** [comment]
Thanks for your question, I've written some of the above details into the readme in my latest update. See all the gory [details](https://github.com/blakeNaccarato/pylance-stubs-unofficial#how-i-update-these-stubs) below the fold over at the readme.
