### ISSUE TITLE
reference to pandas-stubs

### ISSUE THREAD

**Issue by Dr-Irv** [blakeNaccarato/pylance-stubs-unofficial#4]
The `pandas` stubs are placed into the `pylance` distribution by taking them from the `pandas-stubs` project.  https://github.com/pandas-dev/pandas-stubs

We release new stubs every few weeks, and then it takes Microsoft a week or two to take our new release and put it in their distribution.

So it would be better for people to always install the latest `pandas-stubs` from pypi or conda-forge rather than taking anything from here.

**Comment by blakeNaccarato** [comment]
Yes, the stubs in each release of this repo are pinned to the exact stubs that happened to be bundled with Pylance every time they make a release, which are themselves somewhat out of date from the very latest stubs from various sources. Although my focus here is not to always have the latest stubs, but rather for each commit/release here to help unify the behavior of vanilla `pyright` running in CI and Pylance running locally.

So if the user is making local code decisions informed by Pylance `v2023.4.40`, when they push, their CI can work with the same stubs checked out from the corresponding tag in this repo, and results should be almost identical to what the user had running locally (barring some minor differences due to Pylance having non-trivial/unknown stub composition behind the scenes).

Although I do agree it is valuable to intentionally keep newer stubs where possible, and having `pandas-stubs` in your project `requirements.txt` or equivalent is a good idea! I could document this in the readme, indicating best practices _in addition to_ checking out stubs from this repo in your CI.

I have a question to this end. Can a combination like `pandas==1.5.3` and `pandas-stubs==2.0.0.230412` coexist? Or does the `pandas-stubs` version have to share its first three version numbers with the `pandas` install? If `pandas-stubs` _has to_ track `pandas` version exactly, then keeping them in lockstep with simple dependency management by Dependabot/Renovate/etc. could be a bit non-trivial.

**Comment by Dr-Irv** [comment]
> Although I do agree it is valuable to intentionally keep newer stubs where possible, and having pandas-stubs in your project requirements.txt or equivalent is a good idea! I could document this in the readme, indicating best practices in addition to checking out stubs from this repo in your CI.

We had a report in pandas-stubs where someone thought that your repo was the one containing the stubs, so anything in your docs that tells people to report issues with the pandas stubs in the pandas-stubs project would be useful.


> I have a question to this end. Can a combination like `pandas==1.5.3` and `pandas-stubs==2.0.0.230412` coexist? Or does the `pandas-stubs` version have to share its first three version numbers with the `pandas` install? If `pandas-stubs` _has to_ track `pandas` version exactly, then keeping them in lockstep with simple dependency management by Dependabot/Renovate/etc. could be a bit non-trivial.

The way that we are managing the versioning is that a `pandas-stubs` version of `x.y.z.YYMMDD` means "these are stubs compatible with version x.y.z of pandas, and the stubs were released on MM/DD/YY".   

So if you have a dependency on version x.y.z of pandas,  you should use the last released version of pandas-stubs corresponding to version x.y.z.  A release of pandas-stubs where x or y were increased will include deprecations and API changes that might be incompatible with the older version of pandas.

In the case of 1.5.3, we won't be doing any more releases that support 1.5.3, which means that if you type checked your code, and it failed because of an error in the stubs, that error would only be fixed in new releases (next one will be 2.0.1.YYMMDD at some point).

I hope that makes sense.

**Comment by blakeNaccarato** [comment]
Ah, okay. Let me see if I'm understanding this properly:

- Someone uses this repo as their `typings` submodule
- They have a type stub related issue, say with Pandas (or https://github.com/microsoft/python-type-stubs, for example)
- They open an issue over in your repo (or https://github.com/microsoft/python-type-stubs, for example) about the stub problem
- The issue may (or may not) be resolved if only they were using the latest stubs from `pandas-stubs` (or https://github.com/microsoft/python-type-stubs, for example)

So since the purpose of this repo is to track the state of the Pylance extension stubs, it will necessarily lag the latest stubs available, and can cause users to create noise on other repos such as yours. I guess this is the same problem with Pylance itself, a user of VSCode could have a problem with Pylance type checking something in Pandas, and open an issue when it may already be handled by the latest `pandas-stubs`. The moving target of evolving type stubs is tough to communicate to users who just want to make the squiggly lines go away, of course.

Am I getting that right?

A solution would be for me to add a disclaimer to the readme, indicating the express purpose of this repo (to track Pylance), and that for any particular type stub issues encountered, try fetching the latest stubs from the related source before opening an issue.

**Comment by Dr-Irv** [comment]
> Am I getting that right?

I think so.

> A solution would be for me to add a disclaimer to the readme, indicating the express purpose of this repo (to track Pylance), and that for any particular type stub issues encountered, try fetching the latest stubs from the related source before opening an issue.

Yes, I think that would help.  I'm just trying to make people aware that the official stubs for pandas are in pandas-stubs and nowhere else.

**Comment by blakeNaccarato** [comment]
I see, I will try to make that clear in the readme. I suspect that the Pylance team are periodically grabbing stubs from https://github.com/pandas-dev/pandas-stubs/tree/main/pandas-stubs and bundling/vendoring them with Pylance releases, to sidestep the need to `pip install pandas-stubs` and keep it in lockstep with the version of Pandas you have installed. Is it the case that the stubs bundled with Pylance will only lag your stubs by a week or two at most?

I'm sure it causes headaches though, that every VSCode user has no idea what "version" of `pandas-stubs` they're using behind the scenes.

A sensible middle-ground solution (aside from Pylance ripping out their bundled `pandas-stubs` entirely) would be if the Pylance team could include the `pandas-stubs` version they bundle in the VSCode Output window for debug purposes? That way you could instruct VSCode users to have their `pandas-stubs` version ready when opening an Issue.

But yes, I will at least recommend that users manually pin `pandas-stubs` in their project requirements and keep it in step with their `pandas` version in the readme.

**Comment by Dr-Irv** [comment]
> I see, I will try to make that clear in the readme. I suspect that the Pylance team are periodically grabbing stubs from https://github.com/pandas-dev/pandas-stubs/tree/main/pandas-stubs and bundling/vendoring them with Pylance releases, to sidestep the need to `pip install pandas-stubs` and keep it in lockstep with the version of Pandas you have installed. Is it the case that the stubs bundled with Pylance will only lag your stubs by a week or two at most?

Yes, I think they are doing a weekly release and pre-release.  The pre-release from one week becomes the release in the following week.  For the pre-release (done on Wednesdays), they grab what is in the repo at that time.  
> 
> I'm sure it causes headaches though, that every VSCode user has no idea what "version" of `pandas-stubs` they're using behind the scenes.

Yes, because we do have a string called `_stub_version` in `pandas-stubs/_version.pyi` that is the version number, but it is the version number of the last release, and isn't updated with each commit.  
> 
> A sensible middle-ground solution (aside from Pylance ripping out their bundled `pandas-stubs` entirely) would be if the Pylance team could include the `pandas-stubs` version they bundle in the VSCode Output window for debug purposes? That way you could instruct VSCode users to have their `pandas-stubs` version ready when opening an Issue.

In VSCode, you can do 
```python
from pandas._version import _stub_version
reveal_type(_stub_version)
```
and then the Problems section will show the version of the stubs that was included (less any more recent commits)

> 
> But yes, I will at least recommend that users manually pin `pandas-stubs` in their project requirements and keep it in step with their `pandas` version in the readme.

Also, if someone installs `pandas-stubs`, then the installed version will override whatever is bundled with pylance.

**Comment by blakeNaccarato** [comment]
Okay I made a general recommendation regarding out-of-date stubs, and specifically recommended the installation of `pandas-stubs~=#.#.#` where `#.#.#` corresponds to the user's Pandas version, which should grab the latest valid stubs for that version.
